// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTAEVuGYIsC0cBet249Mj_YP_9o3yv4Q',
    appId: '1:791028381623:web:299cfd2edc315e93529a32',
    messagingSenderId: '791028381623',
    projectId: 'physiomed-project',
    authDomain: 'physiomed-project.firebaseapp.com',
    storageBucket: 'physiomed-project.appspot.com',
    measurementId: 'G-MR7H2CTRL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxVtcL45OwSIrz07JuNUQ9V6DutTbbBM',
    appId: '1:791028381623:android:fcb822c7df96f704529a32',
    messagingSenderId: '791028381623',
    projectId: 'physiomed-project',
    storageBucket: 'physiomed-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzaTrnE2GCvcDfIwCBeIMrJEp147E3lc',
    appId: '1:791028381623:ios:be449ea8fb9cf682529a32',
    messagingSenderId: '791028381623',
    projectId: 'physiomed-project',
    storageBucket: 'physiomed-project.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuzaTrnE2GCvcDfIwCBeIMrJEp147E3lc',
    appId: '1:791028381623:ios:be449ea8fb9cf682529a32',
    messagingSenderId: '791028381623',
    projectId: 'physiomed-project',
    storageBucket: 'physiomed-project.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTAEVuGYIsC0cBet249Mj_YP_9o3yv4Q',
    appId: '1:791028381623:web:a168646464c09864529a32',
    messagingSenderId: '791028381623',
    projectId: 'physiomed-project',
    authDomain: 'physiomed-project.firebaseapp.com',
    storageBucket: 'physiomed-project.appspot.com',
    measurementId: 'G-BMWGSJN00Y',
  );
}
